image: "gitpod/workspace-bun"

tasks:
  - name: "Install dependencies"
    before: |
    init: "bun install"

vscode:
  extensions:
    - "esbenp.prettier-vscode"
    - "NomicFoundation.hardhat-solidity"
